packages:
  # all packages in subdirs of packages/ and components/
  - 'applications/**'
  - 'plugins/**'
  - 'packages/**'
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
